version: "3.8"

services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/device
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db

  migrate:
    build: .
    command: npx prisma migrate deploy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/device
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: device
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
